
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>IVCA History</title>
<meta name="Author" content="Brian Rosenberg">
<meta name="Copyright" content="Brian Rosenberg 2013">
<meta name="Description" content="International Veteran Cycle Association">
<meta name="Keywords" content="IVCA, Veteran Cycle, Vintage Cycle, Bicycle, Club, IVCA, International Veteran Cycle Association">
        
<link rel="stylesheet" type="text/css" href="css/ivca.css"/>
</head>
<body>
   
    <?php 
  include ("topNav.htm");
?>

  <div id="bodytext" style="top:200px">                    
<p >The History of the IVCA Rallies begins in 1981</p>
<p >The first formal International Veteran Cycle Rally (IVCR) was held in 1981 at Grantham, England, the then home of the National Cycle Museum, who together with Trust House Forte, sponsored the rally. Entries were received from Australia, Belgium, France, Germany, Spain and the UK. A total 50 riders took part, 27 of whom rode pre-1870 Velocipedes. <br><br>The second event, held in 1982 in Ulis, France, was sponsored by Carrefour and the Museum du V�locip�de. 107 riders took part from Belgium, France, Germany, Italy, Japan, Netherlands, Spain, Switzerland and the UK and this time 37 were riding Pre-1870 bicycles. <br><br>In 1983 the third event should have been held at Dinant in Belgium but it was cancelled and an event was promoted at Rothley in Leicestershire, England and run in conjunction with the UK National Veteran Cycle Rally. As it was a dual event, the 25 riders from France, Japan and Switzerland entered the International Rally and the British entered the National Rally, which brought the total number of participants to over 200. <br><br>England again held the rally again in 1984 at Harlow, sponsored by the Mark Hall Cycle Museum, the National Cycle Museum and BP. 66 riders from Germany, the Netherlands and the UK took part of which ten rode pre-1870 cycles. <br><br>Both the Swiss and the Dutch organised International Rallies in 1985. The Swiss event was held at Aegerital, near Lucerne with a date restriction of pre-1925. It was at this rally that Bernard Barbeau proposed the formation of an international organisation. A meeting was held and the International Veteran Cycle Association provisionally came into being with Gerard Buisset being elected as the first President and Bernard Barbeau, the man whose idea founded the Association, as the Secretary-Treasurer. The Dutch event held at Valkenswaard was organised on the lines of previous rallies, sponsored by Gazelle. Dommelsche, Cosmos Computers, Brabant Pers C. and Vredestein. Riders came from Belgium, Germany, Indonesia, Netherlands, UK and USA and over 150 were riding pre-1890 solid tyred cycles, of which over 60 were high bicycles. Because of these two events, the idea was formulated to allow the IVCA to co-ordinate international rallies. </p>
<p style="text-align:center" ><img title="" src="../jpg/1372595615.jpg" alt="" width="333" height="253"><img title="" src="../jpg/1372597463.jpg" alt="" width="328" height="253"></p>
<p >In 1986 the International Rally should have been held in Germany, but due to difficulties was transferred to England. It was held at the National Exhibition Centre, Birmingham where rides up to 100 miles and races and a parade for Ordinaries were held and then to Lincoln where sponsored by The National Cycle Museum and Lincoln City Council the evening assembly was held. It was at this meeting that the International Veteran Cycle Association was officially founded to communicate on all matters relating to old cycles <br>between museums, clubs and individuals interested in cycle history. The&nbsp;officers provisionally elected in 1985, were confirmed. Participants came from Belgium, France, Germany, Netherlands, Switzerland, UK and the USA. <br><br>The seventh International Veteran Cycle Rally in 1987 was held in Nijmegen, Netherlands and was sponsored by the Velorama Museum. Entrants came from Belgium, France, Germany, Japan, Netherlands, Switzerland, UK and USA. <br><br>1988, the eighth IVCR was held in Blois, France and hosted by the Union V�locip�dique Belle �poque, had riders from Belgium, France, Germany, Japan, Netherlands Switzerland, UK and USA. <br><br>1989, the ninth IVCR was held in Lenk, Switzerland and included entrants from Belgium, France, Germany, Netherlands, UK and USA. <br><br>In 1990, the tenth IVCR was the celebration of the 150<sup>th</sup> anniversary of the Macmillan bicycle and was held at Drumlanrig Castle, Scotland. Sponsored by the Scottish Tourist Board entrants came from Australia, Belgium, Czechoslovakia, Denmark, England, France, Germany, Ireland, Japan, Luxembourg, Netherlands, Spain, Sweden, Switzerland and USA. <br><br>1991 and the eleventh IVCR was held in Finlay, Ohio, USA. Based at the University it was part of a 'Victorian Celebration' and hosted by The Wheelmen. Approximately 400 people took part, coming from Belgium, Czechoslovakia, France, Ireland, Japan, Netherlands, UK and USA. <br><br>A European Rally was also held at Hannover, Germany which drew entrants from Belgium, France, Japan, Netherlands, Switzerland, UK and USA. <br><br>The twelfth IVCR in 1992 was held in Gent, Belgium. Hosted by the Gentsche Retro Wielen and sponsored by Opel and Schwinn. Over 250 entrants took part from Austria, Belgium, Czechoslovakia, Denmark, France, Ireland, Netherlands, Switzerland, UK and USA. <br><br>In 1993, the 13<sup>th</sup> IVCR was held at Zbraslev, near Prague in the Czech Republic, sponsored by Mars. Over 300 people came to take part from Austria, Belgium, Canada, France, Germany, Ireland, Netherlands, Switzerland, UK and USA. <br><br>1994, the 14<sup>th</sup> IVCR returned to England to be hosted by the Peterborough Vintage Cycle Club and held at the East of England Showground, supported by numerous sponsors. Over 220 participants took part from Australia, Austria, Belgium, Canada, Czech Republic, France, Germany, Ireland, Netherlands, Switzerland, UK, and USA.</p>
<p style="text-align:center" ><img title="" src="../jpg/1372597387.jpg" alt="" width="383" height="279"><img title="" src="../jpg/1372597405.jpg" alt="" width="351" height="280"></p>
<p >1995. The 15<sup>th</sup> IVCR was held near Haarlem in the Netherlands and formed part of the 750<sup>th</sup> year celebrations of the city of Haarlem. It attracted about 300 participants from Australia, Austria, Belgium, Czech Republic, France, Germany, Ireland, Netherlands, Switzerland, UK, USA <br><br>1996. The 16<sup>th</sup> IVCR was held at Wiesbaden, Germany and organised by the Veteranen Fahrzeug Verband, it attracted over 200 participants from Austria, Belgium, Czech Republic, France, Germany, Ireland, Netherlands, Sweden, Switzerland, UK and USA.&nbsp;<br><br>In 1997 the IVCR was held in Appenzell, Switzerland, organised by the Velo-Veteranen Club Schweiz and supported by the Appenzeller Cheese Company. 218 entries were received from Austria, Australia, Belgium, Czech Republic, France, Germany, Ireland, Netherlands, Sweden, Switzerland, UK and USA. <br><br>The 1998 IVCR was held in Zwettl in Austria, organised by BIKE Waldviertel and supported by the towns of Zwettl and Raabs. 234 entries were received from Austria, Australia, Belgium, Czech Republic, France, Germany, Ireland, Netherlands, Sweden, Switzerland, UK and USA. <br><br>In 1999 the IVCR returned to La Chaus�e St Victor, near Blois in France and was organised by the Union V�locip�dique Belle �poque, the highlight being the costumed ride to the Chateau de Chambord. Some 350 riders took part from at least twelve different countries. <br><br>2000 saw the IVCR return to the United States as part of the Wheelmen National Meet at Salisbury, Maryland. Blessed by very warm and dry weather, some 280 riders took part from Australia, Canada, the Czech Republic, Germany, Switzerland, the UK and USA. <br><br>The Favorit organisation sponsored the rally in 2001 in Brno in the Czech Republic. Over 200 riders took part, many from the Czech Republic and neighbouring Slovakia, but also from Australia, Canada, Germany, Switzerland, the UK and USA. <br><br>The 22nd IVCR turned to Roeselare, Belgium. About 350 cyclefriends from Austria, Belgium, Canada, the Czech Republic, France, Germany, Japan, Netherlands, Slovakia, Sweden, Switzerland, the UK and USA enjoyed the Rally. <br><br>In 2003 the IVCR went to Beechworth, Victoria, Australia organized by Vintage Cycle Club of Victoria. Over 100 friends from Australia, Austria, Belgium, Czech Republik, Germany, Ireland, Netherlands, New Zealand, Switzerland, UK and USA came down under and enjoyes the Shimano Australia sponsored Rallye. The Races was held in Evandale, Tasmania. <br><br>The 24<sup>th</sup> Rally was organized by the Sport Event Organizer Herbert Lackner and his team in Rust at Neusiedler Lake, Austria. About 270 riders from Australia, Austria, Belgium, Canada, Czech Republic, France, Germany, Hungary, Ireland, Netherlands, Slovakia, Switzerland, UK and USA. <br><br>The 25<sup>th</sup> Rally was in 2005 held in Bad Br�ckenau, Germany at the Deutches Fahrrad Museum.</p>
<p >The 26<sup>th</sup> IVCA meet was held in conjunction with the Wheelmen annual meet at Waterloo, Ontario, Canada 12-16 July, 2006. This was the first time that either group had visited Canada. Organizer was Glen Norcliffe. The first day - century day � began with heavy rainfall, but ended in sunshine, and the rest of the week was warm and sunny. Thursday saw a group ride to St Jacob�s, a Mennonite village, followed by a picnic and races. A swop meet on Friday morning was followed by a choice of a) a Victorian tea at the birthplace of Canada�s most famous prime minister; b) a 30 mile ride to Ontario�s last covered bridge, or c) a visit to the local Brick Brewery. Saturday began with the official photo, followed by a ride to the city centre for a demonstration of cycling. After a picnic lunch games were held in the afternoon and finally a German style banquet was held in the Transylvania Club.</p>
<p style="text-align:center" ><img title="" src="../jpg/1372597504.jpg" alt="" width="388" height="293"><img title="" src="../jpg/1372597426.jpg" alt="" width="224" height="290"></p>
<p >In 2007 Sweden was supposed to be the organizers but due to local misunderstandings and problems the organizers withdraw their proposal and in stead the rally was held in the village Oirschot in Netherlands</p>
<p >In 2008 the 28th rally was in Beaulieu, England. 13 countries were represented with 206 participants in total, from UK, USA, Switzerland, New Zealand, Netherlands, Ireland, Germany, France, Denmark, Czech Republic, Canada, Belgium and Austria.</p>
<p >In 2009 the rally was in Neuchatel, Switzerland</p>
<p >In 2010 the 30th IVCA rally was held in Denmark; the first Scandinavian country to host an IVCA rally. The small village Hjerteberg on the Isle of Møn was the venue for the rally. The organizer was Brian Rosenberg and the vintage bicycle club Dansk Veterancykel Klub. The rally was sponsored by local dealers&nbsp;from the Isle of&nbsp;M�n and Nyord and the Tourist Bureau of M�n. In total 155 participants from USA, UK, New Zealand, Australia, Belgium, Canada, Denmark, France, Netherlands, Ireland, Switzerland, Sweden, Czech Rep., Germany, Hungary and for the first time Norway. From the program: Day 1: Welcome and races of High Bicycles and Hobby Horses. Day 2: The Century Ride (100/75/50/25 miles) from Hjertebjerg to the Isle of Nyord. Day 3: Visit at the local School of Hjertebjerg and a Picnic Ride to the Geocenter M�n at the White Cliffs of M�n. Day 4: Costume Ride to and sightseeing in Stege. <a href="http://www.cykelfestival.dk/">Homepage</a></p>
<p >In 2011 the rally was ment to be in Slovakia but paticipants from Slovakia didn't attend to any of the rallies since 2006 the IVCA commitee lost communication with the organizers of Slovakia and it was decided&nbsp;to find a&nbsp;new country to host the rally.&nbsp;The rally was then organized by Alain Cuvier, France. It was from 1 to 4 June 2011 that the small village of La Ferte Imbault hosted the 31st IVCA Rally&nbsp;in sunny weather. Located in the heart of the Sologne, the place was ideal to receive more than two hundred participants from 16 countries who to discover the charms of the region known for hunting and fishing, castles, forests and camping at the edge of a pond.The Century took place on a 17 km lap of a small forest road; some participants even saw wild boars. The second day, after a large market and a picnic in the park of the castle, the race took place on a 700m circuit in an ambiance of celebration. On the last day, a 40 km costume ride took the participants through the historic town of Romorantin and to the Matra Automobile Museum. During the evening a show full of surprises closed this event under the sign of friendship and conviviality. <a href="http://www.ivca2011.com/" target="_blank">Homepage</a></p>
<p >The 32d rally was held in the medieval city of Gent in Belgium at the Blaarmeersen (a BLOSO sport facility domain in the heart of the city). The organizers were Dirk Van Luchem and Jean Van de Perre and the members of the 3 mayor bicycle clubs in Belgium.&nbsp; 254 participants from 18 countries&nbsp;including participation of Indonesia with a 12 men delegation enjoyed a wonderful rally that started on Wednesday with a welcome drink with multiple Belgian ales in different styles followed by a warm diner. On Thursday, the century ride (100/75/50/25 miles), was held over country roads and a taste of the famous cobble stones in Flanders. Friday morning there was a massive jumble and Friday afternoon were held the races on a 600 m track on the Blaarmeersen. Saturday was the day of the historic ride into the center of Gent with local refreshments and a lunch served in the Quick. A visit to the local Brewery was much appreciated by most of the participants. With one of the longest gala diners ever, this event ended on Sunday morning.</p>
<p >The 33<sup>rd</sup> IVCA Rally 2013 took place in the Czech Republic for the third time already this time in south-moravian town Veselí nad Moravou. The Town Veselí itself was the main event organizer. The chairmans of the preparation committee were Josef Zimovcák and the mayor of the town Miloš Kozumplík. The leaders of individual implementation groups were Jaroslav Miklenda, Vladimír Bednarík and Vojtìška Ricicová. The event was financially supported by Town Veselí, South Moravian and Zlín Region and last but not least by private persons. 198 participants from 17 countries (Canada, Great Britain, France, Belgium, Netherlands, Denmark, Sweden, Norway, Germany, Switzerland, Austria, Poland, Slovakia, Hungary, Russia, Indonesia and Czech Republic) entered the Rally; up to 220 people, including event organizers and helpers, participated in the races and rides. All guests arrived on the first day and in the evening there was an opening ceremony; the 100-Miles-Race on the circuit of 20 kms took place on the second day the route was Veselí nad Moravou – Kozojídky – Hroznová Lhota – Knìždub - Tasov; the third day was dedicated to the flea market in the centre of the town and to the English-Mile-Race (on the cca 530m long closed circuit near the campsite); and on the fourth day, there was a costume ride through Uherský Ostroh, Ostrožská Nová Ves and Kunovice to Uherské Hradištì and back. All the evenings had a common denominator – music and entertainment - only at different places (twice the sports hall, after that the wine cellar in Bzenec and the Saturday gala evening took place in the culture house).&nbsp; The inhabitants of the villages along the 100-Miles-Track and Costume Ride Track had prepared very interesting program for the participants, as well. The „dances“ on high wheels (CKV 1880 Praha) and on safety bicycles (VBC Zbraslav) were amazing and interesting for all the guests of the event. <a href="http://www.ivcarally2013.cz/" target="_blank">Homepage</a></p>
<p ><img title="" src="../jpg/1372597553.jpg" alt=""></p>
<p>The 34<sup>th</sup> Rally was held the first time in Hungary at Tiszakeczke. Hot springs and the beautiful landscape of the Tisza illustated the races.
Participants from Austria, Australia, Belgium, Canada, Czech Republik, Danmark, France, Germany, Hungary, Indonesia, Ireland, Poland, Russia, Slovakia, Sweden, Switzerland, USA and UK enjoyed the extraordinary selection of bicycles from all Hungary presented in a hall.</p>

<p>The 35<sup>th</sup> Rally was held in Sölvesborg, Sweden by the Swedish Club Cykelhistoriska Föreningen. Riders from 16 countries took part. <a href="http://cykelhistoriska.se/old/ivca2015.html">IVCA 2015</a></p>

<p>The 36<sup>th</sup> Rally was held in Moscow, Russia. At the Exhibition Area VDNKh, a theme park in Moscow with the charm of the 1950s. About 90 international participants from Austria, Belgium, Czech Republic, France, Germany, Indonesia, the Netherlands, Norway, Switzerland, USA and the UK attended.</p>

<p>The 200<sup>th</sup> anniversary of the Laufmaschine was celebrated by the 37<sup>th</sup> Rallye at Karlsruhe, Baden, Germany, the birthplace of Karl Freiherr von Drais. About 450 participants enjoyed the Grand Ducel Garden and Castle coming from Austria, Australia, Belgium, Canada, Czech Republic, Denmark, France, Germany, Hungary, Italy, Indonesia, Ireland, Japan, the Netherlands, Norway, Poland, Russia, Slovakia, Switzerland, USA and the UK. - IVCA Rally 2017 in Karlsruhe</p>

<p>The 38<sup>th</sup> was the first Rally held in Asia was organized by KOSTI, the indonesian club at Sanur, Bali. About 8.000 indonesian riders took parkand presented their country to the cycling world. International guests arrived from Australia, Belgium, Czech Republic, Denmark, France, Germany, Japan, Malaysia, the Netherlands, New Zealand, Switzerland, USA and the UK. </p>
</div> 
</body>

</html>